### ISSUE TITLE
The app is not full screen

### ISSUE THREAD

**Issue by yui2000** [Voltranex/McCabeThiele#1]
I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
Here is my screenshot: 
https://imgur.com/6h6E56l
https://imgur.com/kk1rovx
The app is very useful to me, I love it if you could fix this issue.
Thank you in advance.

**Comment by Voltranex** [comment]
what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10

**Comment by Voltranex** [comment]
> I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
> Here is my screenshot:
> https://imgur.com/6h6E56l
> https://imgur.com/kk1rovx
> The app is very useful to me, I love it if you could fix this issue.
> Thank you in advance.

**Hey, what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10**

**Comment by yui2000** [comment]
> > I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
> > Here is my screenshot:
> > https://imgur.com/6h6E56l
> > https://imgur.com/kk1rovx
> > The app is very useful to me, I love it if you could fix this issue.
> > Thank you in advance.
> 
> **Hey, what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10**

Mine is 100%
Resolution 1366 x 768

**Comment by Voltranex** [comment]
> > > I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
> > > Here is my screenshot:
> > > https://imgur.com/6h6E56l
> > > https://imgur.com/kk1rovx
> > > The app is very useful to me, I love it if you could fix this issue.
> > > Thank you in advance.
> > 
> > 
> > **Hey, what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10**
> 
> Mine is 100%
> Resolution 1366 x 768

Hey, i have shared FLARE for different screen resolution, can you test the 1366 x 768 version ? please let me know any problem occurs.

link : https://github.com/Voltranex/McCabeThiele-FLARE/releases/tag/for-matlab-users-resolution

**Comment by yui2000** [comment]
> > > > I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
> > > > Here is my screenshot:
> > > > https://imgur.com/6h6E56l
> > > > https://imgur.com/kk1rovx
> > > > The app is very useful to me, I love it if you could fix this issue.
> > > > Thank you in advance.
> > > 
> > > 
> > > **Hey, what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10**
> > 
> > 
> > Mine is 100%
> > Resolution 1366 x 768
> 
> Hey, i have shared FLARE for different screen resolution, can you test the 1366 x 768 version ? please let me know any problem occurs.
> 
> link : https://github.com/Voltranex/McCabeThiele-FLARE/releases/tag/for-matlab-users-resolution

It's working perfectly now. It means a lot to me. Thank you again.
Could I ask the last question? How can I save the diagram into image or just zoom out to see the detail?

**Comment by Voltranex** [comment]
> > > > > I'm using MATLAB R2018a and try to launch full screen window but it wasn't working.
> > > > > Here is my screenshot:
> > > > > https://imgur.com/6h6E56l
> > > > > https://imgur.com/kk1rovx
> > > > > The app is very useful to me, I love it if you could fix this issue.
> > > > > Thank you in advance.
> > > > 
> > > > 
> > > > **Hey, what is your screen resolution and scale and layout value shown here : https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10**
> > > 
> > > 
> > > Mine is 100%
> > > Resolution 1366 x 768
> > 
> > Hey, i have shared FLARE for different screen resolution, can you test the 1366 x 768 version ? please let me know any problem occurs.
> > 
> > link : https://github.com/Voltranex/McCabeThiele-FLARE/releases/tag/for-matlab-users-resolution
> 
> It's working perfectly now. It means a lot to me. Thank you again.
> Could I ask the last question? How can I save the diagram into image or just zoom out to see the detail?

No problem at all, thank you for your interest. Well actually i think that when i was developing but the image export location is choosen MATLAB directory. If it is possible to users choose that option i would like to add it. For now you can take screenshot of it.
